# Generated by Django 4.2 on 2024-08-31 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoryasi', 'verbose_name_plural': 'Kategoryalar'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Komment', 'verbose_name_plural': 'Kommentlar'},
        ),
        migrations.AlterModelOptions(
            name='janr',
            options={'verbose_name': 'Janri', 'verbose_name_plural': 'Janrlar'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Kinosi', 'verbose_name_plural': 'Kinolar'},
        ),
    ]
