# Generated by Django 4.2 on 2024-09-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_alter_category_options_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
